name: KitDuels
version: ${project.version}
main: com.github.imdabigboss.kitduels.spigot.KitDuels
api-version: 1.17
softdepend: [VoidGenerator, WorldEdit, HolographicDisplays]
depend: [floodgate]

commands:
  kd:
    permission: kitduels.kd
  kdkits:
    permission: kitduels.kdkits
  joingame:
    permission: kitduels.joingame
  leavegame:
    permission: kitduels.leavegame
  kitselect:
    permission: kitduels.kitselect
  kdstats:
    permission: kitduels.kdstats

permissions:
  kitduels.kd:
    default: op
  kitduels.kdkits:
    default: op
  kitduels.joingame:
    default: true
  kitduels.leavegame:
    default: true
  kitduels.kitselect:
    default: true
  kitduels.kdstats:
    default: true